[#97] Hotfix for ipv6
equetzal/huronOS-build-tools pull request #115
Opened 2023-06-11 03:59 UTC by DT3264

[#97] Hotfix for ipv6

2023-06-11 04:03 UTC, DT3264 commented
Is DROP mode when we actually allow specific sites to access the internet and drop connection to the rest?

2023-06-12 02:12 UTC, equetzal requested changes
Overall good, but let's remove the function to the the directives variable. We can use `hos-dvar` or the `get_directives_var` that it's already included on `libhapply.so`

2023-06-12 02:12 UTC, equetzal commented on base-system/usrroot/usr/lib/hsync/libhfirewall.so
> +get_directives_var() {
Why do we want this here? It is already available on the other libraries.

2023-06-12 02:12 UTC, equetzal commented on base-system/usrroot/usr/lib/hsync/libhfirewall.so
> +	"
Nice, we should copy this to the case when filtering. On line 191.

2023-06-13 08:02 UTC, merged