Updating eclipse software files
equetzal/huronOS-build-tools pull request #170
Opened 2023-08-04 15:19 UTC by DT3264

Updating eclipse software files

This PR
* Updates eclipse to download the tar file from the eclipseide site instead of a local file in the software folder

2023-08-08 02:47 UTC, equetzal approved these changes
LGTM!

2023-08-09 07:33 UTC, DT3264 commented
@equetzal I updated the script to avoid any need for ui interaction as seen on the ioi image, so i think a re-review might be worth,
I already tested this version and works just fine.

2023-08-10 00:52 UTC, equetzal requested changes
Amazing PR, Good work on this! :) 
Let's keep a look into the IOI vm code so that we can learn a bit more how are they doing things.

Requesting changes as the files are on the PR not related to the PR. After remove, AC.

2023-08-10 00:52 UTC, equetzal commented on software-modules/base/03-budgie/files/autostart/autosetup.desktop
How is this file related to eclipse? 
If it's not related, please delete it from the PR. You uncommit it, delete the files, the commit it again and then link it with `sl pr link 170` (with the new commit checked out)
You can also use sl split but I've not used it.

2023-08-10 00:52 UTC, equetzal commented on software-modules/programming/eclipse/eclipse.sh
Amazing work on this!, This was something really needed!
One step more to automate builds!

2023-08-10 15:06 UTC, DT3264 commented on software-modules/base/03-budgie/files/autostart/autosetup.desktop
Whops, i don't know how those files ended up in that PR :sweat_smile: 
Deleting those

2023-08-10 17:18 UTC, equetzal approved these changes

2023-08-10 17:44 UTC, merged